#! /bin/bash
# Quick script to do a complete build for the bt-test
#   testing program
#

origFldr=$PWD
userNm=${HOME##*/}
bdate=$(date +%Y%m%d)

if [ -d "bt-test" -o -d "uni-utils" ]; then
    baseFldr=$origFldr
else
    baseFldr=${origFldr%/bt-test*}
    if [ "$baseFldr" == "$origFldr" ]; then
        baseFldr=${origFldr%/uni-utils*}
        if [ "$baseFldr" == "$origFldr" ]; then
            echo "Can not find the bt-test or uni-utils folders in the path, "
            echo "so exiting with error indicated."
            exit 1
        fi
    fi
fi
echo "origFldr is $origFldr and baseFldr is $baseFldr"

cd $baseFldr

getout () {
    echo "The executing process failed stopping here"
    exit 1
}

# The libfoutil.a library needs to be deleted as it can cause a number of
#   confusing build error messages when building a checked out commit
#   that is different enough from the previous build.
rm lib/libbtutil.a

cd uni-utils/src
echo "Running compiler g++ -std=c++17 -c -I../include hex-symbol.cc in $PWD"
g++ -O2 -Wall -std=c++17 -c -I../include hex-symbol.cc || getout
echo "Running compiler g++ -std=c++17 -I../include uni-utils.cc in $PWD"
g++ -O2 -Wall -std=c++17 -c -I../include uni-utils.cc || getout
echo "Updating the library ar -Prs ~/data/lib/libfoutil.a hex-symbol.o in $PWD"
ar -Prs ../../lib/libbtutil.a hex-symbol.o uni-utils.o

cd $baseFldr/bt-test/src
echo "Running compiler g++ -std=c++17 -c -I../include fo-utils.cc in $PWD"
g++ -O2 -Wall -std=c++17 -c -I../include fo-utils.cc || getout

echo "Updating library ar -Prs ~/data/lib/libfoutil.a ncursio.o btree-graph-class.o"
ar -Prs ../../lib/libbtutil.a fo-utils.o
ar -Ptv ../../lib/libbtutil.a

echo "Running compiler g++ -std=c++17 -o $baseFldr/tstr tstr.cc -L ../../lib -lbtutil in $PWD"
g++ -O2 -Wall -std=c++17 -I../include -o $baseFldr/tstr tstr.cc -L ../../lib -lbtutil

cd $baseFldr
